### ISSUE TITLE
Where to download the training and validation samples?

### ISSUE THREAD

**Issue by hnyz979** [bryanyzhu/deepOF#3]
Dear Dr.Zhu
I am interested in deepOF and I downloaded your codes. However, I found that the step "assert(os.path.exists(img_path))" reports an error. It seems that this means that there are no img_paths, which is used for storing the training samples. May I know where to download there samples?
Thanks in advance.

**Comment by hnyz979** [comment]
oops... sorry for not seeing your paper before. Now I know the download address. Sorry for disterbing.

**Comment by hnyz979** [comment]
oops... sorry for not seeing your paper before. Now I know the download address. Sorry for disturbing.

**Comment by bryanyzhu** [comment]
No problem, glad you found it.
