### ISSUE TITLE
a read me file.

### ISSUE THREAD

**Issue by panna19951227** [bryanyzhu/deepOF#5]
Hello,
I want to replicate it for my own dataset. The codes listed here are very difficult to understand. Could you please include a read me file.

**Comment by bryanyzhu** [comment]
I am sorry that I didn't see this. I am glad you found this repo, but I suggest you to use other repos like

https://github.com/simonmeister/UnFlow
https://github.com/tinghuiz/SfMLearner
https://github.com/yzcjtr/GeoNet

These repos are all tensorflow based, and have state-of-the-art performance. 

My repo is kind of out-dated, in terms of both methodology and tensorflow version.
